name: Pipeline Python Avançada

on:
  push:
    branches:
      - main

jobs:
  executar-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Verificar versão do Python
        run: python --version

      - name: Listar arquivos do projeto
        run: ls

      - name: Executar script principal
        run: python app.py

      - name: Exibir mensagem final
        run: echo "Pipeline concluída com sucesso!"