name: Pipeline Python Simples

on:
  push:
    branches:
      - main

jobs:
  executar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Configurar ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Executar script Python
        run: python app.py